# Generated by Django 3.2.9 on 2021-11-26 18:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('service_descricao', models.TextField(verbose_name='Descrição')),
                ('data_public', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Publicação')),
                ('service_imagem', models.ImageField(blank=True, default='default.png', null=True, upload_to='imagens/%Y/%m/%d', verbose_name='Imagem')),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.category', verbose_name='Categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.usuario', verbose_name='Usuário')),
            ],
        ),
    ]
